spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_tracker
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: true

logging:
  level:
    com.gymtracker: DEBUG
